### ISSUE TITLE
Comments on the netifd integration script

### ISSUE THREAD

**Issue by zorun** [danrl/luci-proto-wireguard#5]
Hi,

I finally got the time to test your script.  On the whole, it works fine, thanks!

I just have a few comments on the code:

- the kernel module for wireguard should be loaded automatically on boot, why do you need to check and load it manually?
- `route_allowed_ips` expects a string named "enabled" in your script, but it's fundamentally a boolean.  You should use `config_get_bool`.
- nested functions do not look good (`configure_peer()` inside `proto_wireguard_setup()`), is it necessary?  I'm actually surprised it works at all with ash.
- I think you should change `addresses` to `ipaddr` and `ip6addr`, to be more consistent with other protos.  See https://wiki.openwrt.org/doc/uci/network#protocol_static and https://wiki.openwrt.org/doc/uci/network#multiple_ip_addresses
- can you avoid the `tr` hack to separate address and subnet length?  As a minimum, you should use the shell builtin string replacement, like `${address/\// }`.  It would avoid the cost of spawning a subshell and launching an external command.  Even better would be to avoid transforming the addresses and prefixes at all, but I didn't find alternatives to `proto_add_ipv{4,6}_{address,route}` (I guess you also looked for that :) )
- just a minor thing: other tunneling proto generally have a `ifname` argument to be able to choose the interface name, with a suitable default.  Here, you took the approach to have a hardcoded `wg-$configsection` for the interface name.  I'm actually fine with that, I don't think it's worth the effort to support arbitrary interface names.

**Comment by zorun** [comment]
By the way, other proto seem to declare all their config option with their type in `proto_l2tp_init_config`, for instance: https://github.com/openwrt/packages/blob/master/net/xl2tpd/files/l2tp.sh#L11
I'm not sure how it is used, maybe for syntax/type checking?

Also, regarding IP address configuration, it seems that other proto don't do it, they let netifd handle this.  For instance, here is an example L2TP configuration in `/etc/network/interfaces` using the `xl2tpd` package:

```
config interface myl2tp
	option proto		l2tp
	option server		XX.XX.XX.XX
	option username		"username"
	option password		"password"
	option ipv6		1
	option keepalive	10
	option mtu		1460

config interface myl2tp_static
	option proto		static
	option ifname		@myl2tp
	option ipaddr		YY.YY.YY.YY/32
	option ip6addr		'2001:db8:42::2/64'
	option ip6prefix	'2001:db8:42::/48'
	list   dns		ZZ.ZZ.ZZ.ZZ
```

See also https://wiki.openwrt.org/doc/uci/network#static_addressing_of_a_gre_tunnel

The advantage is that you don't have to implement all this complex logic to manage addresses, since it's already been implemented in netifd.  Also, you don't want to reimplement all possible options of "proto static": https://wiki.openwrt.org/doc/uci/network#protocol_static

**Comment by bol-van** [comment]
I support all that was said. To be professional solution must comply with openwrt standards.

**Comment by danrl** [comment]
Guys, I have been very busy today with other things. However, I briefly fixed most of the issues. Code isn't ready yet, but will push soon.

@zorun 
> the kernel module for wireguard should be loaded automatically on boot

Perfect!  I removed that part. 

> route_allowed_ips  / bool

fixed.

> nested functions

They work fine, but I moved the code to a separate function. Better safe than sorry.

> static config

I removed the "addresses" variable. The WireGuard interface now comes *without* any IP addresses. You can create a static configuration including all the OpenWRT magic of static protocols by creating a separate interface (e.g. foo_static) selecting "static" as protocol and "foo" as underlying interface. I think it is good to keep those things separated and I really do not want to (a) implement static myself nor (b) move back to a static light where I was yesterday.

> `${address/\// }`

In the working. Funny errors I had, that's why I went with 'tr'. Will look into it again. Time to go from prototype to perfection, eh?

> proto_add_ipv{4,6}_{address,route} (I guess you also looked for that :) )

I wish there would be something. Meh. netifd's proto_ functions are not exactly endless fun to use.

> ifname

I don't mind. Removed the `wg-`. Users are now free to name their interfaces within the usual constrains. Good catch!

@bol-van 
> I support all that was said. To be professional solution must comply with openwrt standards.

Agreed. I just wished those weren't scattered over different sites and wikis and whatever. We are getting there.


New bullet to dodge: `proto_add_host_depedency()`
* does not like IPv6 addresses in general
* or does not like IPv6 adresses if there isn't a GU address on wan/wan6

I had to disable (comment out) the endpoint depedenency feature @bol-van asked for recently.
I will not commit code that does not handle IPv6, I am so fed up with IPv4 that I will for sure not push anything that does break when someone uses state-of-the-art IP. Will reach out to netifd folks to further investigate what the deal is with `proto_add_host_depedency()`. Can't figure it out right now.
Anyone got an idea? I don't have records of my tests, but I am almost sure it worked with dual stack before.

**Comment by danrl** [comment]
@zorun 
> By the way, other proto seem to declare all their config option with their type in proto_l2tp_init_config

I think it is only needed for the json thingy. It won't work for the peer configs, but it does not really matter for the _setup() function, so I switched to json for _setup(). Not that I think that it makes any difference, but if that's en par with the other protocols' setup functions I am fine with that.

Pushed the latest code (working copy, not the final one).

**Comment by danrl** [comment]
@zorun 
> ${address/\// }

```
      case "${allowed_ip}" in
        *:*/*)
          proto_add_ipv6_route "${allowed_ip%%/*}" "${allowed_ip##*/}"
        ;;
        */*)
          proto_add_ipv4_route "${allowed_ip%%/*}" "${allowed_ip##*/}"
        ;;
      esac
```

**Comment by zorun** [comment]
Thanks for the update!  I like your new solution for the `proto_add_ipv{4,6}_route` arguments :)
